server:
  port: 80

# 开启降级feign.hystrix
feign:
  hystrix:
    enabled: true
# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false   #不向Eureka中注册自己

